// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_rope_q(
    device const float* input_in [[buffer(0)]],
    device const float* rope_table_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 960) {
    return;
  }
uint o = id;
uint row = o / 960u;
uint col = o % 960u;
uint pair = (col % 64u) / 2u;
uint rem2 = (col % 64u) % 2u;
    float cos_t = rope_table_in[((row * 32u + pair) * 3u) + 1u];
    float sin_t = rope_table_in[((row * 32u + pair) * 3u) + 2u];
    if (rem2 == 0u) {
        output[o] = (input_in[row * 960u + col] * cos_t) - (input_in[row * 960u + (col + 1u)] * sin_t);
    } else {
        output[o] = (input_in[row * 960u + (col - 1u)] * sin_t) + (input_in[row * 960u + col] * cos_t);
    }
}
