// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_context_gemm(
    device const float* probabilities_in [[buffer(0)]],
    device const float* values_in [[buffer(1)]],
    device float* output [[buffer(2)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
  if (i >= 4) {
    return;
  }
float acc = 0.0;
uint col = id.x;
uint row = 0u;
for (uint k_tile = 0u; k_tile < 136u; k_tile++) {
    uint k_start = k_tile * 8u;
    for (uint kk = 0u; kk < 8u; kk++) {
        uint a_k = k_start + kk;
        uint b_idx = a_k * 320u + col;
        if (col < 64u && a_k < 1088u) { acc += probabilities_in[a_k] * values_in[b_idx]; }
    }
}
uint out_idx = row * 64u + col;
if (col < 64u) { output[out_idx] = acc; }
}
