// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void prefill_causal_softmax(
    device const float* scores_in [[buffer(0)]],
    device const float* causal_mask_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 1296) {
    return;
  }
uint o = id;
uint row = o / 36u;
uint col = o % 36u;
float row_max = (scores_in[row * 36u + 0u] + causal_mask_in[row * 36u + 0u]);
for (uint j = 1u; j < 36u; j++) {
    row_max = max(row_max, (scores_in[row * 36u + j] + causal_mask_in[row * 36u + j]));
}
float row_sum = 0.0;
for (uint j = 0u; j < 36u; j++) {
    row_sum += exp((scores_in[row * 36u + j] + causal_mask_in[row * 36u + j]) - row_max);
}
output[o] = exp((scores_in[row * 36u + col] + causal_mask_in[row * 36u + col]) - row_max) / row_sum;
}
