// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void prefill_gemm_qo(
    device const float* input_in [[buffer(0)]],
    device const float* weights_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device const float* _gea3_plan_extra_1 [[buffer(3)]],
    device float* output [[buffer(4)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
threadgroup float simd_stage_a[128];
threadgroup float simd_stage_b[128];
threadgroup float simd_parts[128];
simdgroup_float8x8 simd_acc = make_filled_simdgroup_matrix<float, 8>(0.0f);
uint row = id.y;
uint col = id.x;
uint ty = local_id.y;
uint tx = local_id.x;
uint simd_lane = ty * 8u + tx;
uint simd_group = simd_lane / 32u;
uint row_base = row - ty;
uint col_base = col - tx;
if ((row_base + 8u <= 36u) && (col_base + 8u <= 960u)) {
    for (uint kt = simd_group; kt < 120u; kt += 2u) {
        simdgroup_float8x8 sa; simdgroup_float8x8 sb;
        simdgroup_load(sa, input_in, 960u, ulong2(kt * 8u, row_base), false);
        simdgroup_load(sb, weights_in, 960u, ulong2(kt * 8u, col_base), true);
        simdgroup_multiply_accumulate(simd_acc, sa, sb, simd_acc);
    }
} else {
    for (uint kt = 0u; kt < 120u; kt++) {
        uint k_start = kt * 8u;
        uint parity = kt % 2u;
        if (simd_lane < 32u) {
            if (simd_lane < 16u) {
                uint r = simd_lane / 2u; uint c4 = simd_lane % 2u;
                uint gr = row_base + r;
                float4 v = float4(0.0f);
                if (gr < 36u) { v = ((const device float4*)(input_in + gr * 960u + k_start))[c4]; }
                simd_stage_a[parity * 64u + r * 8u + c4 * 4u + 0u] = v.x;
                simd_stage_a[parity * 64u + r * 8u + c4 * 4u + 1u] = v.y;
                simd_stage_a[parity * 64u + r * 8u + c4 * 4u + 2u] = v.z;
                simd_stage_a[parity * 64u + r * 8u + c4 * 4u + 3u] = v.w;
            } else {
                uint l = simd_lane - 16u;
                uint c = l / 2u; uint k4 = l % 2u;
                uint gc = col_base + c;
                float4 v = float4(0.0f);
                if (gc < 960u) { v = ((const device float4*)(weights_in + gc * 960u + k_start))[k4]; }
                simd_stage_b[parity * 64u + c * 8u + k4 * 4u + 0u] = v.x;
                simd_stage_b[parity * 64u + c * 8u + k4 * 4u + 1u] = v.y;
                simd_stage_b[parity * 64u + c * 8u + k4 * 4u + 2u] = v.z;
                simd_stage_b[parity * 64u + c * 8u + k4 * 4u + 3u] = v.w;
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        if (parity == simd_group) {
            simdgroup_float8x8 sa; simdgroup_float8x8 sb;
            simdgroup_load(sa, simd_stage_a + parity * 64u, 8u, ulong2(0u, 0u), false);
            simdgroup_load(sb, simd_stage_b + parity * 64u, 8u, ulong2(0u, 0u), true);
            simdgroup_multiply_accumulate(simd_acc, sa, sb, simd_acc);
        }
    }
}
simdgroup_store(simd_acc, simd_parts + simd_group * 64u, 8u, ulong2(0u, 0u), false);
threadgroup_barrier(mem_flags::mem_threadgroup);
float acc = simd_parts[simd_lane] + simd_parts[64u + simd_lane];
uint out_idx = row * 960u + col;
if (row < 36u && col < 960u) { output[out_idx] = acc; }
}
