// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_key_transpose(
    device const float* input_in [[buffer(0)]],
    device float* output [[buffer(1)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 70400) {
    return;
  }
uint k = id;
uint i = k % 1100u;
uint j = k / 1100u;
output[k] = input_in[i * 320u + j];
}
