// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void prefill_head_rmsnorm(
    device const float* input_in [[buffer(0)]],
    device const float* weight_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device const float* _gea3_plan_extra_1 [[buffer(3)]],
    device float* output [[buffer(4)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 34560) {
    return;
  }
uint o = id;
uint row = o / 960u;
uint col = o % 960u;
float sumsq = 0.0;
for (uint j = 0u; j < 960u; j++) {
    float xj = input_in[row * 960u + j];
    sumsq += xj * xj;
}
float mean = sumsq / float(960u);
float scale = 1.0 / sqrt(mean + 0.000009999999747378752f);
output[o] = input_in[row * 960u + col] * scale * weight_in[col];
}
