// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_score_gemm(
    device const float* query_in [[buffer(0)]],
    device const float* key_transposed_in [[buffer(1)]],
    device const float* attention_scale_in [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
  if (i >= 5) {
    return;
  }
float acc = 0.0;
uint col = id.x;
uint row = 0u;
for (uint k_tile = 0u; k_tile < 8u; k_tile++) {
    uint k_start = k_tile * 8u;
    for (uint kk = 0u; kk < 8u; kk++) {
        uint a_k = k_start + kk;
        uint b_idx = a_k * 76u + col;
        if (col < 76u && a_k < 64u) { acc += query_in[a_k] * key_transposed_in[b_idx]; }
    }
}
uint out_idx = row * 76u + col;
if (row < 1u && col < 76u) {
        output[out_idx] = (acc * attention_scale_in[out_idx]);
    }
}
