// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_gemv_gate_up(
    device const float* input_in [[buffer(0)]],
    device const float* weights_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device const float* _gea3_plan_extra_1 [[buffer(3)]],
    device float* output [[buffer(4)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
  if (i >= 160) {
    return;
  }
float acc = 0.0;
uint col = id.x;
uint row = 0u;
for (uint k_tile = 0u; k_tile < 120u; k_tile++) {
    uint k_start = k_tile * 8u;
    for (uint kk = 0u; kk < 8u; kk++) {
        uint a_k = k_start + kk;
        uint b_idx = col * 960u + a_k;
        if (col < 2560u && a_k < 960u) { acc += input_in[a_k] * weights_in[b_idx]; }
    }
}
uint out_idx = row * 2560u + col;
if (col < 2560u) { output[out_idx] = acc; }
}
