// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void embedding_gather(
    device const float* selector_in [[buffer(0)]],
    device const float* embeddings_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
  if (i >= 60) {
    return;
  }
float acc = 0.0;
uint col = id.x;
uint row = 0u;
for (uint k_tile = 0u; k_tile < 6144u; k_tile++) {
    uint k_start = k_tile * 8u;
    for (uint kk = 0u; kk < 8u; kk++) {
        uint a_k = k_start + kk;
        uint b_idx = a_k * 960u + col;
        if (col < 960u && a_k < 49152u) { acc += selector_in[a_k] * embeddings_in[b_idx]; }
    }
}
uint out_idx = row * 960u + col;
if (col < 960u) { output[out_idx] = acc; }
}
