// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void kv_append_v(
    device const float* history_in [[buffer(0)]],
    device const float* slot_in [[buffer(1)]],
    device const float* row_in [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 352000) {
    return;
  }
    output[id] = (history_in[id] + row_in[id]);
}
