// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_context_gemm(
    device const float* probabilities_in [[buffer(0)]],
    device const float* values_in [[buffer(1)]],
    device float* output [[buffer(2)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
threadgroup float shared_a[64];
threadgroup float shared_b[64];
float acc = 0.0;
uint row = id.y;
uint col = id.x;
uint ty = local_id.y;
uint tx = local_id.x;
for (uint k_tile = 0u; k_tile < 10u; k_tile++) {
    uint k_start = k_tile * 8u;
    uint a_idx = row * 76u + (k_start + tx);
    if (a_idx < 1u * 76u) { shared_a[ty * 8u + tx] = probabilities_in[a_idx]; }
    if (a_idx >= 1u * 76u) { shared_a[ty * 8u + tx] = 0.0; }
    for (uint gemv_ty = 0u; gemv_ty < 8u; gemv_ty++) {
    uint b_idx = (k_start + gemv_ty) * 320u + col;
    if (col < 64u && (k_start + gemv_ty) < 76u) { shared_b[gemv_ty * 8u + tx] = values_in[b_idx]; }
    if (col >= 64u || (k_start + gemv_ty) >= 76u) { shared_b[gemv_ty * 8u + tx] = 0.0; }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint kk = 0u; kk < 8u; kk++) {
        acc += shared_a[ty * 8u + kk] * shared_b[kk * 8u + tx];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
}
uint out_idx = row * 64u + col;
if (row < 1u && col < 64u) { output[out_idx] = acc; }
}
