// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_masked_softmax(
    device const float* scores_in [[buffer(0)]],
    device const float* length_mask_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 76) {
    return;
  }
uint o = id;
uint row = o / 76u;
uint col = o % 76u;
float row_max = (scores_in[row * 76u + 0u] + length_mask_in[row * 76u + 0u]);
for (uint j = 1u; j < 76u; j++) {
    row_max = max(row_max, (scores_in[row * 76u + j] + length_mask_in[row * 76u + j]));
}
float row_sum = 0.0;
for (uint j = 0u; j < 76u; j++) {
    row_sum += exp((scores_in[row * 76u + j] + length_mask_in[row * 76u + j]) - row_max);
}
output[o] = exp((scores_in[row * 76u + col] + length_mask_in[row * 76u + col]) - row_max) / row_sum;
}
