// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void decode_residual_add(
    device const float* left_in [[buffer(0)]],
    device const float* right_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 960) {
    return;
  }
    output[id] = (left_in[id] + right_in[id]);
}
