// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void prefill_kv_write_v(
    device const float* history_in [[buffer(0)]],
    device const float* block_in [[buffer(1)]],
    device const float* rows_in [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
threadgroup float shared_a[64];
threadgroup float shared_b[64];
float acc = 0.0;
uint row = id.y;
uint col = id.x;
uint ty = local_id.y;
uint tx = local_id.x;
for (uint k_tile = 0u; k_tile < 5u; k_tile++) {
    uint k_start = k_tile * 8u;
    uint a_idx = row * 36u + (k_start + tx);
    if (a_idx < 76u * 36u) { shared_a[ty * 8u + tx] = block_in[a_idx]; }
    if (a_idx >= 76u * 36u) { shared_a[ty * 8u + tx] = 0.0; }
    uint b_idx = (k_start + ty) * 320u + col;
    if (col < 320u && (k_start + ty) < 36u) { shared_b[ty * 8u + tx] = rows_in[b_idx]; }
    if (col >= 320u || (k_start + ty) >= 36u) { shared_b[ty * 8u + tx] = 0.0; }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint kk = 0u; kk < 8u; kk++) {
        acc += shared_a[ty * 8u + kk] * shared_b[kk * 8u + tx];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
}
uint out_idx = row * 320u + col;
if (row < 76u && col < 320u) {
        output[out_idx] = (history_in[out_idx] + acc);
    }
}
