// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void prefill_embedding_gather(
    device const float* embeddings_in [[buffer(0)]],
    device const uint* ids_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 34560) {
    return;
  }
uint o = id;
uint row = o / 960u;
uint col = o % 960u;
uint token = ids_in[row];
output[o] = embeddings_in[token * 960u + col];
}
