// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void kv_append_v(
    device const float* history_in [[buffer(0)]],
    device const float* slot_in [[buffer(1)]],
    device const float* row_in [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
float acc = 0.0;
uint row = id.y;
uint col = id.x;
if (row < 76u && col < 320u) { acc = slot_in[row] * row_in[col]; }
uint out_idx = row * 320u + col;
if (row < 76u && col < 320u) {
        output[out_idx] = (history_in[out_idx] + acc);
    }
}
