// Generated by radix metal-text launch variant (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void embedding_gather(
    device const float* selector_in [[buffer(0)]],
    device const float* embeddings_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint3 id [[thread_position_in_grid]],
    uint3 local_id [[thread_position_in_threadgroup]]
) {
    uint i = id.x;
threadgroup float shared_a[64];
threadgroup float shared_b[64];
float acc = 0.0;
uint row = id.y;
uint col = id.x;
uint ty = local_id.y;
uint tx = local_id.x;
for (uint k_tile = 0u; k_tile < 6144u; k_tile++) {
    uint k_start = k_tile * 8u;
    uint a_idx = row * 49152u + (k_start + tx);
    if (a_idx < 1u * 49152u) { shared_a[ty * 8u + tx] = selector_in[a_idx]; }
    if (a_idx >= 1u * 49152u) { shared_a[ty * 8u + tx] = 0.0; }
    for (uint gemv_ty = 0u; gemv_ty < 8u; gemv_ty++) {
    uint b_idx = (k_start + gemv_ty) * 960u + col;
    if (col < 960u && (k_start + gemv_ty) < 49152u) { shared_b[gemv_ty * 8u + tx] = embeddings_in[b_idx]; }
    if (col >= 960u || (k_start + gemv_ty) >= 49152u) { shared_b[gemv_ty * 8u + tx] = 0.0; }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint kk = 0u; kk < 8u; kk++) {
        acc += shared_a[ty * 8u + kk] * shared_b[kk * 8u + tx];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
}
uint out_idx = row * 960u + col;
if (row < 1u && col < 960u) { output[out_idx] = acc; }
}
