// Generated by radix metal-text (supported-with-limitations compute source).
#include <metal_stdlib>
using namespace metal;

kernel void prefill_swiglu(
    device const float* gate_in [[buffer(0)]],
    device const float* up_in [[buffer(1)]],
    device const float* _gea3_plan_extra_0 [[buffer(2)]],
    device float* output [[buffer(3)]],
    uint id [[thread_position_in_grid]]
) {
  if (id >= 92160) {
    return;
  }
    output[id] = ((gate_in[id] / (exp((-gate_in[id])) + 1.0f)) * up_in[id]);
}
